import { Injectable, Logger } from '@nestjs/common';
import axios from 'axios';
import { DiscoveryService } from '../discovery/discovery.service';

interface DocSource {
    name: string;
    serviceName: string;
    /** Used only when Consul has no healthy instance registered. */
    fallback: string;
}

/**
 * Builds a single OpenAPI document by fetching each downstream microservice's own
 * `/api/docs-json` (generated by its local SwaggerModule) and merging them under the
 * Gateway's public `/api/v1/*` paths. Resolves each service's address dynamically via
 * Consul, the same way the proxy does, so this stays correct as instances change.
 */
@Injectable()
export class DocsAggregatorService {
    private readonly logger = new Logger(DocsAggregatorService.name);
    private cache: { document: Record<string, any>; expiresAt: number } | null = null;
    private readonly cacheTtlMs = 30_000;

    private readonly sources: DocSource[] = [
        { name: 'Accommodation', serviceName: 'accommodation', fallback: process.env.ACCOMMODATION_SERVICE_URL ?? 'http://accommodation:4001' },
        { name: 'Finance', serviceName: 'finance', fallback: process.env.FINANCE_SERVICE_URL ?? 'http://finance:4003' },
    ];

    constructor(private readonly discovery: DiscoveryService) {}

    async getAggregatedDocument(): Promise<Record<string, any>> {
        if (this.cache && this.cache.expiresAt > Date.now()) {
            return this.cache.document;
        }

        const document: Record<string, any> = {
            openapi: '3.0.0',
            info: {
                title: 'Another Home API',
                description:
                    'Unified API documentation aggregated live from every downstream microservice, reached through the API Gateway at /api/v1/*. Regenerated periodically — a service that is down or not yet built simply drops out of this document instead of breaking it.',
                version: '2.0',
            },
            servers: [{ url: process.env.GATEWAY_PUBLIC_URL ?? 'http://localhost:3001', description: 'API Gateway' }],
            tags: [] as any[],
            paths: {} as Record<string, any>,
            components: {
                schemas: {} as Record<string, any>,
                securitySchemes: {
                    bearerAuth: { type: 'http', scheme: 'bearer', bearerFormat: 'JWT' },
                },
            },
            security: [{ bearerAuth: [] }],
        };

        await Promise.all(this.sources.map((source) => this.mergeSource(source, document)));

        this.cache = { document, expiresAt: Date.now() + this.cacheTtlMs };
        return document;
    }

    private async mergeSource(source: DocSource, document: Record<string, any>): Promise<void> {
        const target = await this.resolveTarget(source);
        try {
            const { data } = await axios.get(`${target}/api/docs-json`, { timeout: 3000 });

            for (const [path, item] of Object.entries<any>(data.paths ?? {})) {
                if (path.startsWith('/health')) continue; // internal-only, not proxied by the gateway
                document.paths[`/api/v1${path}`] = item;
            }

            Object.assign(document.components.schemas, data.components?.schemas ?? {});

            for (const tag of data.tags ?? []) {
                if (!document.tags.some((t: any) => t.name === tag.name)) {
                    document.tags.push(tag);
                }
            }

            this.logger.log(`Merged API docs from "${source.name}" (${target})`);
        } catch (err) {
            this.logger.warn(`Could not fetch API docs from "${source.name}" (${target}): ${err instanceof Error ? err.message : err}`);
        }
    }

    private async resolveTarget(source: DocSource): Promise<string> {
        const instance = await this.discovery.resolve(source.serviceName);
        if (instance) {
            return `http://${instance.address}:${instance.port}`;
        }
        return source.fallback;
    }
}
